import React from "react";
import { icons } from "../../constants/images/Icons";
import { images } from "../../constants/images/Images";
import { useNavigate } from "react-router-dom";

/**
 * Renders a featured product card.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {Object} props.product - The product data.
 * @param {Function} props.formatPrice - The function to format the price.
 * @param {Function} props.getIconComponent - The function to get the icon component.
 * @returns {JSX.Element} The rendered component.
 */
const FeaturedProductCard = ({ product, formatPrice, getIconComponent }) => {
  const navigate = useNavigate();

  const navigateToDetails = () => {
    navigate(`/product/${product.id}`);
    window.scrollTo(0, 0);
  };

  // i should probably move these to a separate file and import them but i'm lazy so i'll just copy them here for now :D
  // THE ABOVE COMMENT WAS GENERATED BY COPILOT (i love you co-pilot)
  // HANDLE FAVOURITE CLICK
  const handleFavouriteClick = (event) => {
    event.stopPropagation();
  };

  // HANDLE SHARE CLICK
  const handleShareClick = (event) => {
    event.stopPropagation();
  };

  // HANDLE VISIT WEBPAGE CLICK
  const handleVisitWebpageClick = (event) => {
    event.stopPropagation();
  };

  return (
    <section
      className="bg-white flex rounded-lg mb-12"
      style={{
        boxShadow:
          "0 -2px 5px rgba(0, 0, 0, 0.1), 0 2px 3px rgba(0, 0, 0, 0.1)",
      }}
    >
      <div className="flex">
        <div onClick={navigateToDetails}>
          <img
            src={images.placeholder}
            alt={product.name || "Placeholder"}
            className="w-72 h-72 rounded-lg"
          />
        </div>
        <div className="w-2/3 flex flex-col justify-between p-6">
          <div onClick={navigateToDetails}>
            <h3 className="text-xl font-black">{product.name}</h3>
            <div className="flex items-center space-x-2">
              <icons.Tag style={{ width: "20px", height: "20px" }} />
              <p className="text-gray-500">
                {product.site?.category?.name || "No category"}
              </p>
            </div>
            <div className="flex items-start mt-6 space-x-4">
              <div className="mr-4">
                <p className="text-gray-500">Current price:</p>
                <p
                  className={`text-2xl text-bold ${
                    product.change_percentage > 0
                      ? "text-red-500"
                      : "text-green-500"
                  }`}
                >
                  {formatPrice(product.current_price)}
                </p>
                <span
                  className={`text-sm ${
                    product.change_percentage > 0
                      ? "text-red-500"
                      : "text-green-500"
                  }`}
                >
                  {product.change_percentage > 0 ? "+" : "-"}
                  {Math.abs(product.change_percentage)}%
                </span>
              </div>
              <div className="flex flex-col">
                <p className="text-gray-500">Current cheapest website:</p>
                <div className="flex items-center">
                  <div className="mr-2">
                    {getIconComponent(product.site?.site_name) &&
                      React.createElement(
                        getIconComponent(product.site.site_name),
                        {
                          style: { width: "20px", height: "20px" },
                        }
                      )}
                  </div>
                  <p className="text-gray-500">
                    {product.site?.site_name || "Unknown"}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-4 flex items-center space-x-2 gap-4">
            <div className="flex flex-row items-center gap-1">
              <icons.Heart
                style={{ width: "20px", height: "20px" }}
                onClick={handleFavouriteClick}
              />
              <a href="#" className="text-black" onClick={handleFavouriteClick}>
                Favourite
              </a>
            </div>
            <div className="flex flex-row items-center gap-1">
              <icons.Link
                style={{ width: "20px", height: "20px" }}
                onClick={handleShareClick}
              />
              <a href="#" className="text-black" onClick={handleShareClick}>
                Share
              </a>
            </div>
            <div className="flex flex-row items-center gap-1">
              <icons.Plane style={{ width: "20px", height: "20px" }} />
              <a
                href={product.url}
                target="_blank"
                className="text-black"
                onClick={handleVisitWebpageClick}
              >
                Visit webpage
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeaturedProductCard;
